# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "1.7.1"

[[constraint]]
  name = "github.com/hanwen/go-fuse"
  revision = "1d35017e97018335f348413b3aeed67468d80f7b"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/tebeka/selenium"
  revision = "a49cf4b98a36c2b21b1ccb012852bd142d5fc04a"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.1"

[[constraint]]
  name = "github.com/teris-io/shortid"
  revision = "771a37caa5cf0c81f585d7b6df4dfc77e0615b5c"

[prune]
  go-tests = true
  unused-packages = true
